### ISSUE TITLE
Check dynamically for plugin updates

### ISSUE THREAD

**Issue by atrautsch** [smartshark/serverSHARK#13] opened 2018-09-06 07:36 UTC
From the PluginView of Admin, use: https://developer.github.com/v3/repos/releases/

**Comment by atrautsch** [comment] 2018-09-06 07:42
It should also be possible to install the new version or new plugins automatically (except for MecoSHARK)

**Comment by sherbold** [comment] 2018-09-13 12:57
Duplicate of issue #6

**Closed by sherbold** 2018-09-13 12:57 UTC
